import { useMounted } from '@/lib/hooks/util';
import { projectsAtom } from '@/lib/jotai/atom';
import { useAtom } from 'jotai';
import type { NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, MouseEvent, useRef } from 'react';

const Home: NextPage = () => {
	const [projects, setprojects] = useAtom(projectsAtom);
	const ref = useRef<HTMLInputElement>(null);
	const isMounted = useMounted();
	// avoid next.js VDOM checking
	if (!isMounted) return null;
	const onSubmint = (event: FormEvent) => {
		event.preventDefault();
		if (ref.current === null) return;
		setprojects(projects.concat([ref.current.value]));
	};
	const onClickClear = (event: MouseEvent) => {
		event.preventDefault();
		setprojects([]);
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header></header>
			<main className="m-6">
				<div className="space-y-4">
					<form onSubmit={onSubmint}>
						<div>
							<label htmlFor="name">Enter your pj name: </label>
							<input
								ref={ref}
								type="text"
								name="name"
								id="name"
								required
								className="p-2 border border-blue-200 rounded-md"
							/>
						</div>
						<input
							type="submit"
							value="add"
							className="p-2 border border-blue-200 rounded-md hover:cursor-pointer active:bg-blue-50"
						/>
					</form>
					<button
						onClick={onClickClear}
						className="p-2 border border-blue-200 rounded-md hover:cursor-pointer active:bg-blue-50"
					>
						clear
					</button>
				</div>
				<ul>
					{projects.map((str, idx) => {
						return <li key={`${str}-${idx}`}>{str}</li>;
					})}
				</ul>
			</main>
			<footer></footer>
		</>
	);
};

export default Home;
