import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
	const router = useRouter();
	const [slug, setslug] = useState<string>();
	useEffect(() => {
		if (typeof router.query.slug !== 'string') return;
		setslug(router.query.slug);
	}, [router.query]);
	return (
		<>
			<Head>
				<title>projects: {slug}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header></header>
			<main className="m-6"></main>
			<footer></footer>
		</>
	);
};

export default Home;
